import { Authority, RTIApplication, FirstAppealApplication } from '../types/rti';

export const MOCK_AUTHORITIES: Authority[] = [
  {
    id: 'auth_mohfw',
    code: 'MOHFW',
    name: 'Ministry of Health and Family Welfare',
    name_en: 'Ministry of Health and Family Welfare',
    name_hi: 'स्वास्थ्य एवं परिवार कल्याण मंत्रालय',
    name_bn: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়',
    name_mr: 'आरोग्य आणि कुटुंब कल्याण मंत्रालय',
    name_te: 'ఆరోగ్య మరియు కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ',
    name_ta: 'சுகாதாரம் மற்றும் குடும்ப நல அமைச்சகம்',
    ministry: 'Ministry of Health & Family Welfare',
    ministry_en: 'Ministry of Health & Family Welfare',
    ministry_hi: 'स्वास्थ्य एवं परिवार कल्याण मंत्रालय',
    ministry_bn: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়',
    ministry_mr: 'आरोग्य आणि कुटुंब कल्याण मंत्रालय',
    ministry_te: 'ఆరోగ్య & కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ',
    ministry_ta: 'சுகாதாரம் மற்றும் குடும்ப நல அமைச்சகம்',
    department: 'Department of Health & Family Welfare',
    type: 'Central Government',
    active: true,
    cpioName: 'Shri Rajesh K. Verma',
    cpioDesignation: 'Director (Public Health) & CPIO',
    cpioEmail: 'rajesh.verma@nic.in',
    cpioPhone: '+91-11-23061234',
    faaName: 'Dr. Sunita Sharma',
    faaDesignation: 'Joint Secretary & First Appellate Authority',
    address: 'Nirman Bhawan, Maulana Azad Road, New Delhi - 110011',
    avgTurnaroundDays: 21,
  },
  {
    id: 'auth_railw',
    code: 'RAILW',
    name: 'Ministry of Railways (Railway Board)',
    name_en: 'Ministry of Railways (Railway Board)',
    name_hi: 'रेल मंत्रालय (रेलवे बोर्ड)',
    name_bn: 'রেল মন্ত্রণালয় (রেলওয়ে বোর্ড)',
    name_mr: 'रेल्वे मंत्रालय (रेल्वे बोर्ड)',
    name_te: 'రైల్వే మంత్రిత్వ శాఖ (రైల్వే బోర్డు)',
    name_ta: 'ரயில்வே அமைச்சகம் (ரயில்வே வாரியம்)',
    ministry: 'Ministry of Railways',
    ministry_en: 'Ministry of Railways',
    ministry_hi: 'रेल मंत्रालय',
    ministry_bn: 'রেল মন্ত্রণালয়',
    ministry_mr: 'रेल्वे मंत्रालय',
    ministry_te: 'రైల్వే మంత్రిత్వ శాఖ',
    ministry_ta: 'ரயில்வே அமைச்சகம்',
    department: 'Railway Board',
    type: 'Central Government',
    active: true,
    cpioName: 'Shri Amitabh Saxena',
    cpioDesignation: 'Executive Director (PG) & CPIO',
    cpioEmail: 'cpio.rb@rb.railnet.gov.in',
    cpioPhone: '+91-11-23384567',
    faaName: 'Ms. Meenakshi Sundaram',
    faaDesignation: 'Principal Executive Director & FAA',
    address: 'Rail Bhawan, Rafi Marg, New Delhi - 110001',
    avgTurnaroundDays: 24,
  },
  {
    id: 'auth_meity',
    code: 'MEITY',
    name: 'Ministry of Electronics and Information Technology',
    name_en: 'Ministry of Electronics and Information Technology',
    name_hi: 'इलेक्ट्रॉनिक्स और सूचना प्रौद्योगिकी मंत्रालय',
    name_bn: 'ইলেকট্রনিক্স ও তথ্য প্রযুক্তি মন্ত্রণালয়',
    name_mr: 'इलेक्ट्रॉनिक्स आणि माहिती तंत्रज्ञान मंत्रालय',
    name_te: 'ఎలక్ట్రానిక్స్ మరియు సమాచార సాంకేతిక మంత్రిత్వ శాఖ',
    name_ta: 'மின்னணு மற்றும் தகவல் தொழில்நுட்ப அமைச்சகம்',
    ministry: 'Ministry of Electronics & IT',
    ministry_en: 'Ministry of Electronics & IT',
    ministry_hi: 'इलेक्ट्रॉनिक्स एवं आईटी मंत्रालय',
    ministry_bn: 'ইলেকট্রনিক্স ও আইটি মন্ত্রণালয়',
    ministry_mr: 'इलेक्ट्रॉनिक्स आणि आयटी मंत्रालय',
    ministry_te: 'ఎలక్ట్రానిక్స్ & ఐటీ మంత్రిత్వ శాఖ',
    ministry_ta: 'மின்னணு & தகவல் தொழில்நுட்ப அமைச்சகம்',
    department: 'Cyber Laws and e-Security Wing',
    type: 'Central Government',
    active: true,
    cpioName: 'Dr. Sanjay Bhasin',
    cpioDesignation: 'Scientist F & CPIO (e-Governance)',
    cpioEmail: 'cpio-meity@meity.gov.in',
    cpioPhone: '+91-11-24360199',
    faaName: 'Shri Anand Kumar Roy',
    faaDesignation: 'Group Coordinator (e-Gov) & FAA',
    address: 'Electronics Niketan, 6 CGO Complex, Lodhi Road, New Delhi - 110003',
    avgTurnaroundDays: 18,
  },
  {
    id: 'auth_dotel',
    code: 'DOTEL',
    name: 'Department of Telecommunications',
    name_en: 'Department of Telecommunications',
    name_hi: 'दूरसंचार विभाग',
    name_bn: 'টেলিযোগাযোগ বিভাগ',
    name_mr: 'दूरसंचार विभाग',
    name_te: 'టెలికమ్యూనికేషన్స్ విభాగం',
    name_ta: 'தொலைத்தொடர்பு துறை',
    ministry: 'Ministry of Communications',
    ministry_en: 'Ministry of Communications',
    ministry_hi: 'संचार मंत्रालय',
    ministry_bn: 'যোগাযোগ মন্ত্রণালয়',
    ministry_mr: 'संचार मंत्रालय',
    ministry_te: 'సమాచార ప్రసారాల మంత్రిత్వ శాఖ',
    ministry_ta: 'தகவல் தொடர்பு அமைச்சகம்',
    department: 'Telecom Policy & Regulation',
    type: 'Central Government',
    active: true,
    cpioName: 'Ms. Priyamvada Joshi',
    cpioDesignation: 'Director (Access Services) & CPIO',
    cpioEmail: 'cpio.dot@gov.in',
    cpioPhone: '+91-11-23036000',
    faaName: 'Shri K. Ramanujam',
    faaDesignation: 'Deputy Director General & FAA',
    address: 'Sanchar Bhawan, 20 Ashoka Road, New Delhi - 110001',
    avgTurnaroundDays: 19,
  },
  {
    id: 'auth_cbicd',
    code: 'CBICD',
    name: 'Central Board of Indirect Taxes and Customs (CBIC)',
    name_en: 'Central Board of Indirect Taxes and Customs (CBIC)',
    name_hi: 'केंद्रीय अप्रत्यक्ष कर और सीमा शुल्क बोर्ड (CBIC)',
    name_bn: 'কেন্দ্রীয় পরোক্ষ কর ও শুল্ক বোর্ড (CBIC)',
    name_mr: 'केंद्रीय अप्रत्यक्ष कर आणि सीमाशुल्क मंडळ (CBIC)',
    name_te: 'సెంట్రల్ బోర్డ్ ఆఫ్ ఇండైరెక్ట్ టాక్సెస్ అండ్ కస్టమ్స్ (CBIC)',
    name_ta: 'மத்திய மறைமுக வரிகள் மற்றும் சுங்க வாரியம் (CBIC)',
    ministry: 'Ministry of Finance',
    ministry_en: 'Ministry of Finance',
    ministry_hi: 'वित्त मंत्रालय',
    ministry_bn: 'অর্থ মন্ত্রণালয়',
    ministry_mr: 'वित्त मंत्रालय',
    ministry_te: 'ఆర్థిక మంత్రిత్వ శాఖ',
    ministry_ta: 'நிதி அமைச்சகம்',
    department: 'Department of Revenue',
    type: 'Central Government',
    active: true,
    cpioName: 'Shri Vivek Murthy',
    cpioDesignation: 'Assistant Commissioner (RTI) & CPIO',
    cpioEmail: 'cpio.cbic@gov.in',
    cpioPhone: '+91-11-23092288',
    faaName: 'Shri D. P. Sengupta',
    faaDesignation: 'Commissioner (Appeals) & FAA',
    address: 'North Block, Central Secretariat, New Delhi - 110001',
    avgTurnaroundDays: 25,
  },
  {
    id: 'auth_morth',
    code: 'MORTH',
    name: 'Ministry of Road Transport and Highways',
    name_en: 'Ministry of Road Transport and Highways',
    name_hi: 'सड़क परिवहन और राजमार्ग मंत्रालय',
    name_bn: 'সড়ক পরিবহন ও মহাসড়ক মন্ত্রণালয়',
    name_mr: 'रस्ते वाहतूक आणि महामार्ग मंत्रालय',
    name_te: 'రహదారి రవాణా మరియు రహదారుల మంత్రిత్వ శాఖ',
    name_ta: 'சாலைப் போக்குவரத்து மற்றும் நெடுஞ்சாலைகள் அமைச்சகம்',
    ministry: 'Ministry of Road Transport & Highways',
    ministry_en: 'Ministry of Road Transport & Highways',
    ministry_hi: 'सड़क परिवहन और राजमार्ग मंत्रालय',
    ministry_bn: 'সড়ক পরিবহন ও মহাসড়ক মন্ত্রণালয়',
    ministry_mr: 'रस्ते वाहतूक आणि महामार्ग मंत्रालय',
    ministry_te: 'రహదారి రవాణా మరియు రహదారుల మంత్రిత్వ శాఖ',
    ministry_ta: 'சாலைப் போக்குவரத்து மற்றும் நெடுஞ்சாலைகள் அமைச்சகம்',
    department: 'National Highways Development Wing',
    type: 'Central Government',
    active: true,
    cpioName: 'Shri Harish Chand',
    cpioDesignation: 'Superintending Engineer & CPIO',
    cpioEmail: 'harish.morth@gov.in',
    cpioPhone: '+91-11-23717777',
    faaName: 'Shri Alok Deepankar',
    faaDesignation: 'Chief Engineer & FAA',
    address: 'Transport Bhawan, 1 Parliament Street, New Delhi - 110001',
    avgTurnaroundDays: 22,
  },
  {
    id: 'auth_minha',
    code: 'MINHA',
    name: 'Ministry of Home Affairs',
    name_en: 'Ministry of Home Affairs',
    name_hi: 'गृह मंत्रालय',
    name_bn: 'স্বরাষ্ট্র মন্ত্রণালয়',
    name_mr: 'गृह मंत्रालय',
    name_te: 'హోం వ్యవహారాల మంత్రిత్వ శాఖ',
    name_ta: 'உள்துறை அமைச்சகம்',
    ministry: 'Ministry of Home Affairs',
    ministry_en: 'Ministry of Home Affairs',
    ministry_hi: 'गृह मंत्रालय',
    ministry_bn: 'স্বরাষ্ট্র মন্ত্রণালয়',
    ministry_mr: 'गृह मंत्रालय',
    ministry_te: 'హోం వ్యవహారాల మంత్రిత్వ శాఖ',
    ministry_ta: 'உள்துறை அமைச்சகம்',
    department: 'Internal Security Division',
    type: 'Central Government',
    active: true,
    cpioName: 'Shri Vikramaditya Rao',
    cpioDesignation: 'Deputy Secretary (IS-I) & CPIO',
    cpioEmail: 'cpio.is@mha.gov.in',
    cpioPhone: '+91-11-23092011',
    faaName: 'Shri Shailesh Kumar',
    faaDesignation: 'Joint Secretary (IS) & FAA',
    address: 'North Block, Central Secretariat, New Delhi - 110001',
    avgTurnaroundDays: 20,
  },
  {
    id: 'auth_doptr',
    code: 'DOPTG',
    name: 'Department of Personnel and Training (DoPT)',
    name_en: 'Department of Personnel and Training (DoPT)',
    name_hi: 'कार्मिक और प्रशिक्षण विभाग (DoPT)',
    name_bn: 'কর্মী ও প্রশিক্ষণ বিভাগ (DoPT)',
    name_mr: 'कार्मिक आणि प्रशिक्षण विभाग (DoPT)',
    name_te: 'పర్సనల్ అండ్ ట్రైనింగ్ విభాగం (DoPT)',
    name_ta: 'பணியாளர் மற்றும் பயிற்சித் துறை (DoPT)',
    ministry: 'Ministry of Personnel, Public Grievances and Pensions',
    ministry_en: 'Ministry of Personnel, Public Grievances and Pensions',
    ministry_hi: 'कार्मिक, लोक शिकायत तथा पेंशन मंत्रालय',
    ministry_bn: 'কর্মী, জনঅভিযোগ ও পেনশন মন্ত্রণালয়',
    ministry_mr: 'कार्मिक, सार्वजनिक तक्रारी आणि पेन्शन मंत्रालय',
    ministry_te: 'సిబ్బంది, ప్రజా ఫిర్యాదులు మరియు పెన్షన్ల మంత్రిత్వ శాఖ',
    ministry_ta: 'பணியாளர், பொதுமக்கள் குறைதீர்ப்பு மற்றும் ஓய்வூதிய அமைச்சகம்',
    department: 'RTI Division',
    type: 'Central Government',
    active: true,
    cpioName: 'Smt. Kavitha Pillai',
    cpioDesignation: 'Under Secretary (RTI) & CPIO',
    cpioEmail: 'usrti-dopt@nic.in',
    cpioPhone: '+91-11-24625540',
    faaName: 'Shri Pawan Kumar',
    faaDesignation: 'Director (RTI) & FAA',
    address: 'Lok Nayak Bhawan, Khan Market, New Delhi - 110003',
    avgTurnaroundDays: 15,
  },
  {
    id: 'auth_moedu',
    code: 'MOEDU',
    name: 'Department of Higher Education',
    name_en: 'Department of Higher Education',
    name_hi: 'उच्चतर शिक्षा विभाग',
    name_bn: 'উচ্চশিক্ষা বিভাগ',
    name_mr: 'उच्च शिक्षण विभाग',
    name_te: 'ఉన్నత విద్యా శాఖ',
    name_ta: 'உயர் கல்வித் துறை',
    ministry: 'Ministry of Education',
    ministry_en: 'Ministry of Education',
    ministry_hi: 'शिक्षा मंत्रालय',
    ministry_bn: 'শিক্ষা মন্ত্রণালয়',
    ministry_mr: 'शिक्षण मंत्रालय',
    ministry_te: 'విద్యా మంత్రిత్వ శాఖ',
    ministry_ta: 'கல்வி அமைச்சகம்',
    department: 'Technical & University Education',
    type: 'Central Government',
    active: true,
    cpioName: 'Shri C. P. Ratnakar',
    cpioDesignation: 'Deputy Secretary (CU) & CPIO',
    cpioEmail: 'cpio.edu@gov.in',
    cpioPhone: '+91-11-23384200',
    faaName: 'Ms. Neeta Prasad',
    faaDesignation: 'Joint Secretary & FAA',
    address: 'Shastri Bhawan, Dr. Rajendra Prasad Road, New Delhi - 110001',
    avgTurnaroundDays: 17,
  }
];

export const INITIAL_APPLICATIONS: RTIApplication[] = [
  // 0. UNDER PROCESSING (Demo Citizen Account)
  {
    registrationNumber: 'DOPTR/R/E/26/00991',
    draftId: 'draft_demo_citizen_01',
    status: 'UNDER_PROCESSING',
    authority: MOCK_AUTHORITIES[7], // DOPTR
    applicant: {
      fullName: 'Demo Citizen',
      gender: 'MALE',
      email: 'demo.citizen@example.com',
      mobile: '9876543210',
      country: 'India',
      state: 'Delhi',
      city: 'New Delhi',
      addressLine1: 'Flat 101, Civil Lines, Central District',
      pincode: '110054',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: { isBpl: false },
    requestText: 'Statistical records on RTI disposal rates, First Appeals pendency, and proactive Section 4 disclosure compliance reports for central ministries in FY 2024-25.',
    supportingDocuments: [],
    applicationFee: 10,
    isBplExempt: false,
    paymentRef: 'UPI/2026/774910',
    paymentMethod: 'UPI',
    filedOn: '2026-08-18T10:00:00Z',
    lastUpdated: '2026-08-20T14:30:00Z',
    timeline: [
      {
        state: 'SUBMITTED',
        title: 'Application Lodged',
        description: 'RTI application filed and ₹10 statutory fee received.',
        at: '2026-08-18T10:00:00Z',
        actor: 'Citizen Portal Gateway',
      },
      {
        state: 'PAYMENT_SUCCESS',
        title: 'Payment Confirmed',
        description: 'Transaction TXN_774910 confirmed via Bharatkosh.',
        at: '2026-08-18T10:00:05Z',
        actor: 'Bharatkosh Gateway',
      },
      {
        state: 'RECEIVED',
        title: 'Received by Nodal Officer',
        description: 'Logged in Central DoPT Register.',
        at: '2026-08-19T09:15:00Z',
        actor: 'Nodal RTI Cell',
      },
      {
        state: 'UNDER_PROCESSING',
        title: 'Under Processing by CPIO',
        description: 'Assigned to Smt. Kavitha Pillai, Under Secretary & CPIO for collation of records.',
        at: '2026-08-20T14:30:00Z',
        actor: 'Smt. Kavitha Pillai (CPIO)',
      },
    ],
    actionRequired: null,
    canAppeal: false,
  },
  // 1. RESPONSE AVAILABLE / CLOSED
  {
    registrationNumber: 'DOTEL/R/2026/10492',
    draftId: 'draft_demo_01',
    status: 'RESPONSE_AVAILABLE',
    authority: MOCK_AUTHORITIES[3], // DOTEL
    applicant: {
      fullName: 'Aarav Sharma',
      gender: 'MALE',
      email: 'aarav.sharma@example.com',
      mobile: '9876543210',
      country: 'India',
      state: 'Delhi',
      city: 'New Delhi',
      addressLine1: 'Flat 402, Kaveri Apartments',
      addressLine2: 'Sector 6, Dwarka',
      pincode: '110075',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: { isBpl: false },
    requestText: 'Kindly furnish details of 5G telecom spectrum allocation guidelines, frequency band auctions held in FY 2024-25, total revenue realized by DoT, and compliance audit reports submitted by telecom service providers.',
    supportingDocuments: [
      {
        fileId: 'doc_101',
        fileName: 'spectrum_auction_reference_note.pdf',
        sizeKb: 340,
        uploadedAt: '2026-07-10T10:14:00Z',
      },
    ],
    applicationFee: 10,
    isBplExempt: false,
    paymentRef: 'UPI/2026/789123849',
    paymentMethod: 'UPI',
    filedOn: '2026-07-10T10:15:30Z',
    lastUpdated: '2026-08-01T15:20:00Z',
    timeline: [
      {
        state: 'PAYMENT_SUCCESS',
        title: 'Application Filed & Payment Confirmed',
        description: 'Application successfully registered with fee ₹10.00 via UPI transaction ref: UPI/2026/789123849.',
        at: '2026-07-10T10:15:30Z',
        actor: 'Citizen Portal Gateway',
      },
      {
        state: 'RECEIVED',
        title: 'Received by Department of Telecommunications',
        description: 'Application receipt acknowledged and forwarded to Nodal CPIO for review.',
        at: '2026-07-11T09:30:00Z',
        actor: 'Nodal RTI Cell, DoT',
      },
      {
        state: 'UNDER_PROCESSING',
        title: 'Assigned to CPIO (Access Services)',
        description: 'Transferred to Ms. Priyamvada Joshi, Director (Access Services) & CPIO for collation of records.',
        at: '2026-07-13T11:45:00Z',
        actor: 'CPIO Secretariat',
      },
      {
        state: 'RESPONSE_AVAILABLE',
        title: 'Official RTI Response Released',
        description: 'CPIO has reviewed and uploaded the formal signed reply along with tabular annexures (6 pages).',
        at: '2026-08-01T15:20:00Z',
        actor: 'Ms. Priyamvada Joshi (CPIO)',
      },
    ],
    actionRequired: null,
    responseDocument: {
      fileId: 'resp_dot_10492',
      fileName: 'DOT_RTI_Reply_Letter_10492.pdf',
      releasedOn: '2026-08-01T15:20:00Z',
      cpioRemarks: 'The requisite information regarding 5G auction receipts (Annexure A) and compliance parameters under Rule 4(2) of the Indian Telegraph Act is enclosed herewith. As per Section 19(1) of the RTI Act 2005, you may appeal within 30 days to the First Appellate Authority if aggrieved.',
      dispatchRef: 'DOT/RTI/AS/2026/8912-A',
    },
    canAppeal: true,
  },

  // 2. ADDITIONAL FEE REQUIRED
  {
    registrationNumber: 'MEITY/R/2026/49201',
    draftId: 'draft_demo_02',
    status: 'ADDITIONAL_FEE_REQUIRED',
    authority: MOCK_AUTHORITIES[2], // MEITY
    applicant: {
      fullName: 'Sunita Mehra',
      gender: 'FEMALE',
      email: 'sunita.mehra@example.com',
      mobile: '9812345678',
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      addressLine1: '32, 4th Main Road, Indiranagar',
      pincode: '560038',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: { isBpl: false },
    requestText: 'Certified copies of meeting minutes, committee evaluations, and vendor proposals submitted for the National Data Governance Framework consultations held between October 2024 and March 2025.',
    supportingDocuments: [],
    applicationFee: 10,
    isBplExempt: false,
    paymentRef: 'RUPAY/2026/339182',
    paymentMethod: 'RUPAY',
    filedOn: '2026-08-05T14:30:00Z',
    lastUpdated: '2026-08-18T11:15:00Z',
    timeline: [
      {
        state: 'PAYMENT_SUCCESS',
        title: 'Application Filed & Fee Received',
        description: 'Initial registration fee of ₹10 received.',
        at: '2026-08-05T14:30:00Z',
        actor: 'Citizen Portal',
      },
      {
        state: 'UNDER_PROCESSING',
        title: 'Records Located by CPIO',
        description: 'Information identified across 24 physical document pages. Additional copy fee calculation made.',
        at: '2026-08-18T10:30:00Z',
        actor: 'Dr. Sanjay Bhasin (CPIO)',
      },
      {
        state: 'ADDITIONAL_FEE_REQUIRED',
        title: 'Demand Notice for Additional Fee (Section 7(3))',
        description: 'Demand of ₹48.00 (24 pages @ ₹2/page) raised under RTI Fee Rules 2012. Citizen requested to deposit fee.',
        at: '2026-08-18T11:15:00Z',
        actor: 'CPIO Secretariat, MeitY',
      },
    ],
    actionRequired: {
      type: 'ADDITIONAL_FEE',
      amount: 48,
      reason: 'Under Section 7(3)(a) of the RTI Act 2005 read with Rule 4 of RTI Rules 2012, 24 pages of certified photostat copies have been collated at the statutory rate of ₹2.00 per page.',
      deadline: '2026-09-17T23:59:59Z',
      feeBreakdown: {
        pages: 24,
        ratePerPage: 2,
      },
    },
    canAppeal: false,
  },

  // 3. SUPPORTING DOCUMENT REQUIRED
  {
    registrationNumber: 'CBICD/R/2026/38102',
    draftId: 'draft_demo_03',
    status: 'SUPPORTING_DOCUMENT_REQUIRED',
    authority: MOCK_AUTHORITIES[4], // CBIC
    applicant: {
      fullName: 'Rameshwar Lal Verma',
      gender: 'MALE',
      email: 'rameshwar.verma@example.com',
      mobile: '9789012345',
      country: 'India',
      state: 'Rajasthan',
      city: 'Jaipur',
      addressLine1: 'B-14, Shastri Nagar',
      pincode: '302016',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: {
      isBpl: true,
      cardNumber: 'BPL/RJ/2021/99410',
      yearOfIssue: '2021',
      issuingAuthority: 'Tehsildar, Jaipur Urban',
      docName: 'bpl_ration_card_scan.pdf',
      docSizeKb: 450,
    },
    requestText: 'Please provide certified copy of GST reconciliation assessment order and recovery notice issued to M/s Verma Traders for financial year 2022-23.',
    supportingDocuments: [],
    applicationFee: 0,
    isBplExempt: true,
    paymentRef: 'BPL_EXEMPT',
    paymentMethod: 'BPL Exemption',
    filedOn: '2026-08-12T09:10:00Z',
    lastUpdated: '2026-08-19T16:00:00Z',
    timeline: [
      {
        state: 'SUBMITTED',
        title: 'BPL Application Registered (Fee Exempt)',
        description: 'Application registered under BPL card category without application fee.',
        at: '2026-08-12T09:10:00Z',
        actor: 'Citizen Portal',
      },
      {
        state: 'SUPPORTING_DOCUMENT_REQUIRED',
        title: 'Authorization Document & Specific Period Required',
        description: 'CPIO observed that authorization letter or proprietor declaration is needed to establish identity for third-party commercial records.',
        at: '2026-08-19T16:00:00Z',
        actor: 'Shri Vivek Murthy (CPIO, CBIC)',
      },
    ],
    actionRequired: {
      type: 'SUPPORTING_DOCUMENT_REQUIRED',
      reason: 'The applicant has sought tax assessment records of a commercial entity. Please upload a signed letter of authorization/proprietorship proof or specify how public interest is involved under Section 8(1)(d)/(j) of the RTI Act.',
      deadline: '2026-09-04T23:59:59Z',
    },
    canAppeal: false,
  },

  // 4. TRANSFERRED
  {
    registrationNumber: 'RAILW/R/2026/89401',
    draftId: 'draft_demo_04',
    status: 'TRANSFERRED',
    authority: MOCK_AUTHORITIES[1], // Railway Board
    applicant: {
      fullName: 'Pooja Iyer',
      gender: 'FEMALE',
      email: 'pooja.iyer@example.com',
      mobile: '9845612378',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Lucknow',
      addressLine1: 'House 88, Hazratganj',
      pincode: '226001',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: { isBpl: false },
    requestText: 'Details of platform shelter maintenance funds allocated and utilized for Lucknow Charbagh Railway Station during 2023-2025 and names of certified structural safety auditing contractors.',
    supportingDocuments: [],
    applicationFee: 10,
    isBplExempt: false,
    paymentRef: 'UPI/2026/998124',
    paymentMethod: 'UPI',
    filedOn: '2026-08-14T11:00:00Z',
    lastUpdated: '2026-08-17T14:40:00Z',
    timeline: [
      {
        state: 'PAYMENT_SUCCESS',
        title: 'Application Filed with Railway Board',
        description: 'Application registered with Central Public Authority (Railway Board).',
        at: '2026-08-14T11:00:00Z',
        actor: 'Citizen Portal',
      },
      {
        state: 'TRANSFERRED',
        title: 'Transferred under Section 6(3) of RTI Act',
        description: 'Subject matter pertains closely to Northern Railway Zonal Administration. Transferred to CPIO, Northern Railway (Lucknow Division).',
        at: '2026-08-17T14:40:00Z',
        actor: 'Shri Amitabh Saxena (Railway Board CPIO)',
      },
    ],
    actionRequired: null,
    transferredTo: {
      registrationNumber: 'NRAIL/R/2026/00481',
      authority: 'Office of the Divisional Railway Manager, Northern Railway, Lucknow (NR-LKO)',
      transferredOn: '2026-08-17T14:40:00Z',
      reason: 'The subject matter of station maintenance, platform allocation, and divisional vendor auditing falls under Northern Railway Division Lucknow jurisdiction.',
      section: 'Section 6(3) of RTI Act, 2005',
    },
    canAppeal: false,
  },

  // 5. MULTIPLE CPIO
  {
    registrationNumber: 'MORTH/R/2026/77219',
    draftId: 'draft_demo_05',
    status: 'MULTIPLE_CPIO',
    authority: MOCK_AUTHORITIES[5], // MORTH
    applicant: {
      fullName: 'Vikramjit Singh',
      gender: 'MALE',
      email: 'vikram.singh@example.com',
      mobile: '9811122233',
      country: 'India',
      state: 'Punjab',
      city: 'Amritsar',
      addressLine1: 'Model Town Extension, Lane 4',
      pincode: '143002',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: { isBpl: false },
    requestText: 'Toll fee collection figures for NH-44 Delhi-Amritsar highway between 2022-2024, breakdown of FASTag revenue sharing with State Government, and pothole maintenance SLA reports.',
    supportingDocuments: [],
    applicationFee: 10,
    isBplExempt: false,
    paymentRef: 'NETBANK/2026/77189',
    paymentMethod: 'NETBANKING',
    filedOn: '2026-08-08T08:30:00Z',
    lastUpdated: '2026-08-15T12:00:00Z',
    timeline: [
      {
        state: 'PAYMENT_SUCCESS',
        title: 'Application Filed',
        description: 'Fee ₹10.00 confirmed via State Bank Net Banking.',
        at: '2026-08-08T08:30:00Z',
        actor: 'Citizen Portal',
      },
      {
        state: 'MULTIPLE_CPIO',
        title: 'Distributed Across Multiple Subject CPIOs',
        description: 'Information queries span both National Highway Authority (NHAI) toll operations and Ministry Road Safety Wing.',
        at: '2026-08-15T12:00:00Z',
        actor: 'Nodal Officer, MoRTH',
      },
    ],
    actionRequired: null,
    childApplications: [
      {
        registrationNumber: 'MORTH/R/2026/77219/1',
        authority: 'National Highways Authority of India (NHAI) - Toll Division',
        cpioName: 'Shri R. K. Bhati (GM - Toll Ops)',
        subject: 'Toll fee collections and FASTag revenue sharing data (Points 1 & 2)',
        status: 'UNDER_PROCESSING',
        transferredOn: '2026-08-15T12:00:00Z',
      },
      {
        registrationNumber: 'MORTH/R/2026/77219/2',
        authority: 'MoRTH - Road Safety and Highway Maintenance Division',
        cpioName: 'Shri K. S. Chauhan (SE - Maintenance)',
        subject: 'Pothole repairs, audit schedules and road quality compliance SLAs (Point 3)',
        status: 'RESPONSE_AVAILABLE',
        transferredOn: '2026-08-15T12:00:00Z',
      },
    ],
    canAppeal: false,
  },

  // 6. RETURNED / REJECTED
  {
    registrationNumber: 'MINHA/R/2026/12093',
    draftId: 'draft_demo_06',
    status: 'RETURNED',
    authority: MOCK_AUTHORITIES[6], // MHA
    applicant: {
      fullName: 'Deepak Nambiar',
      gender: 'MALE',
      email: 'deepak.nambiar@example.com',
      mobile: '9447123987',
      country: 'India',
      state: 'Kerala',
      city: 'Kochi',
      addressLine1: 'Plot 12, Panampilly Nagar',
      pincode: '682036',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: { isBpl: false },
    requestText: 'Operational deployment blueprints, security force positioning rosters, and VIP route intelligence details for special protection group escort details.',
    supportingDocuments: [],
    applicationFee: 10,
    isBplExempt: false,
    paymentRef: 'UPI/2026/110948',
    paymentMethod: 'UPI',
    filedOn: '2026-08-02T16:20:00Z',
    lastUpdated: '2026-08-10T11:00:00Z',
    timeline: [
      {
        state: 'PAYMENT_SUCCESS',
        title: 'Application Submitted',
        description: 'Application received and registered in MHA portal.',
        at: '2026-08-02T16:20:00Z',
        actor: 'Citizen Portal',
      },
      {
        state: 'RETURNED',
        title: 'Information Request Declined under Section 8(1)(a) & 8(1)(g)',
        description: 'The requested information directly pertains to security, sovereignty, and strategic operational deployments exempted by law.',
        at: '2026-08-10T11:00:00Z',
        actor: 'Shri Vikramaditya Rao (CPIO, MHA)',
      },
    ],
    actionRequired: null,
    returnReason: 'The information sought contains operational deployment details of security agencies and falls squarely within the statutory exemption under Section 8(1)(a) (prejudicing sovereignty and integrity of India/security of the State) and Section 8(1)(g) of the RTI Act 2005. Furthermore, intelligence organizations specified in the Second Schedule are exempted under Section 24.',
    returnSection: 'Section 8(1)(a), Section 8(1)(g) & Section 24 of RTI Act, 2005',
    canAppeal: true,
  },

  // 7. UNDER PROCESSING
  {
    registrationNumber: 'DOPTR/R/2026/55120',
    draftId: 'draft_demo_07',
    status: 'UNDER_PROCESSING',
    authority: MOCK_AUTHORITIES[7], // DoPT
    applicant: {
      fullName: 'Ananya Deshmukh',
      gender: 'FEMALE',
      email: 'ananya.deshmukh@example.com',
      mobile: '9820011223',
      country: 'India',
      state: 'Maharashtra',
      city: 'Pune',
      addressLine1: 'Row House 5, Baner Road',
      pincode: '411045',
      category: 'URBAN',
      educationalStatus: 'LITERATE',
    },
    bpl: { isBpl: false },
    requestText: 'Number of First Appeals filed before Central Public Authorities in calendar year 2024, average disposal turnaround time, and total penalty sum imposed by Central Information Commission under Section 20(1).',
    supportingDocuments: [],
    applicationFee: 10,
    isBplExempt: false,
    paymentRef: 'CARD/2026/667123',
    paymentMethod: 'CARD',
    filedOn: '2026-08-19T09:40:00Z',
    lastUpdated: '2026-08-20T14:10:00Z',
    timeline: [
      {
        state: 'PAYMENT_SUCCESS',
        title: 'Application Filed & Fee Confirmed',
        description: 'Payment of ₹10 confirmed via Debit Card.',
        at: '2026-08-19T09:40:00Z',
        actor: 'Citizen Portal',
      },
      {
        state: 'RECEIVED',
        title: 'Received by DoPT RTI Cell',
        description: 'Application queued and logged in Central DoPT Register.',
        at: '2026-08-20T10:00:00Z',
        actor: 'Nodal RTI Cell',
      },
      {
        state: 'UNDER_PROCESSING',
        title: 'Assigned to CPIO (RTI Division)',
        description: 'Assigned to Smt. Kavitha Pillai, Under Secretary & CPIO for report compilation from statistical database.',
        at: '2026-08-20T14:10:00Z',
        actor: 'Smt. Kavitha Pillai (CPIO)',
      },
    ],
    actionRequired: null,
    canAppeal: false,
  },
];

export const INITIAL_APPEALS: FirstAppealApplication[] = [
  {
    appealRegistrationNumber: 'DOTEL/A/2026/00194',
    originalRegistrationNumber: 'DOTEL/R/2026/10492',
    ground: 'INCOMPLETE_INFORMATION',
    groundLabel: 'Incomplete or partial information provided by CPIO',
    appealText: 'The CPIO provided high-level summary tables for 5G auction revenue but omitted the requested audit compliance reports for specific telecom circles in Q3. Requested direction to CPIO to furnish full annexures.',
    applicant: INITIAL_APPLICATIONS[0].applicant,
    authority: MOCK_AUTHORITIES[3],
    faaOfficer: {
      name: 'Shri K. Ramanujam',
      designation: 'Deputy Director General & First Appellate Authority',
      email: 'faa.dot@gov.in',
    },
    status: 'SUBMITTED',
    fee: 0,
    filedOn: '2026-08-15T16:00:00Z',
    timeline: [
      {
        state: 'SUBMITTED',
        title: 'First Appeal Registered under Section 19(1)',
        description: 'First appeal successfully logged without statutory fee (Fee = ₹0).',
        at: '2026-08-15T16:00:00Z',
        actor: 'Citizen Portal',
      },
      {
        state: 'UNDER_PROCESSING',
        title: 'Forwarded to First Appellate Authority (FAA)',
        description: 'Sent to Shri K. Ramanujam, DDG & FAA for appellate review and order.',
        at: '2026-08-16T10:30:00Z',
        actor: 'Appellate Registry, DoT',
      },
    ],
  },
];
